name: Earn Crowns Daily

on:
  # Run daily at 9 AM UTC
  schedule:
    - cron: "0 9 * * *"

  # Allow manual triggering
  workflow_dispatch:
    inputs:
      debug_mode:
        description: "Enable debug mode (visible browser)"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

# Global environment variables to prevent Puppeteer from downloading Chromium
env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
  PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome-stable"

jobs:
  earn-crowns:
    runs-on: ubuntu-latest

    # Timeout after 30 minutes
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-liberation \
            libappindicator3-1 \
            libasound2t64 \
            libatk-bridge2.0-0 \
            libdrm2 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils \
            libgbm1 \
            libxss1 \
            ca-certificates \
            fonts-liberation \
            libappindicator3-1 \
            libasound2t64 \
            libatk-bridge2.0-0 \
            libdrm2 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils \
            libgbm1 \
            libxss1 \
            wget

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Cache Chrome user data
        uses: actions/cache@v4
        with:
          path: .chrome-user-data
          key: chrome-user-data-${{ github.sha }}
          restore-keys: |
            chrome-user-data-

      - name: Create environment file
        run: |
          cat > .env.local << EOF
          WIZARD101_USERNAME=${{ secrets.WIZARD101_USERNAME }}
          WIZARD101_PASSWORD=${{ secrets.WIZARD101_PASSWORD }}
          TWO_CAPTCHA_API_KEY=${{ secrets.TWO_CAPTCHA_API_KEY }}
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          NODE_ENV=production
          DEBUG_MODE=${{ github.event.inputs.debug_mode || 'false' }}
          FORCE_VISIBLE=false
          EOF

      - name: Run earn crowns script
        run: |
          # Set debug flag if enabled
          if [ "${{ inputs.debug_mode }}" = "true" ]; then
            export DEBUG=true
          fi

          # Run the script
          npm run earn-crowns

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: earn-crowns-logs-${{ github.run_number }}
          path: logs/
          retention-days: 30

      - name: Upload quiz answers
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quiz-answers-${{ github.run_number }}
          path: scripts/quiz-answers.json
          retention-days: 30

      - name: Upload debug screenshots
        uses: actions/upload-artifact@v4
        if: always() && (github.event.inputs.debug_mode == 'true' || failure())
        with:
          name: debug-screenshots-${{ github.run_number }}
          path: |
            debug-*.png
            debug-post-recaptcha-solution.png
            *.png

      - name: Upload page HTML artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: page-html-${{ github.run_number }}
          path: |
            post-login-*.html
            post-login-frames-info.txt
            debug-quarantined-*.html
          retention-days: 30
